# 应用服务 WEB 访问端口
server:
  port: 8080

#指定Mybatis的Mapper文件
mybatis:
  mapper-locations: classpath:mappers/*xml
  #指定Mybatis的实体目录
  type-aliases-package: com.zcr.springbootbase.domain

#jdbc配置
spring:
  datasource:
    url: jdbc:mysql://192.168.77.128:3306/SpringBootBaseDB?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: zcr
    password: root
  #redist
  redis:
    host: 192.168.77.128
    port: 6379

#配置日志，查看sql输出日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

